package com.example.model

enum class MatchScoreStatus(val value: Int, val abbr: String, val sportsBookText : String = abbr) {
    SCHEDULED(1, "Canlı"),
    FIRST_HALF(2, "1.Y"),
    SECOND_HALF(3, "2.Y"),
    HALF_TIME(4, "İ.Y"),
    FULL_TIME(5, "MS"),
    ENDED(6, "MS"),
    FIRST_HALF_EXTRA_TIME(7, "UZ 1.Y"),
    HALF_TIME_EXTRA_TIME(8, "UZ İY"),
    SECOND_HALF_EXTRA_TIME(9, "UZ 2.Y"),
    FINISHED_AFTER_EXTRA_TIME(10, "UZMS"),
    PENALTIES(11, "PEN"),
    FINISHED_AFTER_PENALTIES(12, "PENMS"),
    DELAYED(13, "ERT"),
    ABANDONED(14, "İPT"),
    FIRST_PERIOD(15, sportsBookText = "1.Periyot", abbr = "1.P"),
    SECOND_PERIOD(16, sportsBookText = "2.Periyot", abbr = "2.P"),
    THIRD_PERIOD(17, sportsBookText = "3.Periyot", abbr = "3.P"),
    FOURTH_PERIOD(18, sportsBookText = "4.Periyot", abbr = "4.P"),
    FIRST_SET(19, "1.Set"),
    SECOND_SET(20, "2.Set"),
    THIRD_SET(21, "3.Set"),
    FOURTH_SET(22, "4.Set"),
    FIFTH_SET(23, "5.Set"),
    POSTPONED(24, "ERT"),
    STOPPED(25, "DUR"),
    CANCELLED(26, "İPT"),
    THIRD_EXTRA_TIME(27, "3.UZ"),
    FOURTH_EXTRA_TIME(28, "4.UZ"),
    FIFTH_EXTRA_TIME(29, "5.UZ"),
    SIXTH_EXTRA_TIME(30, "6.UZ"),
    SEVENTH_EXTRA_TIME(31, "7.UZ"),
    EIGHTH_EXTRA_TIME(32, "8.UZ"),
    NINTH_EXTRA_TIME(33, "9.UZ"),
    LIVE(34, "CANLI"),
    PRE_EXTRA_TIME(35, "UZ"),
    PRE_PENALTIES(36, "PEN"),
    FIFTH_PERIOD(37,"5.Periyot", "5.P"),
    SIXTH_PERIOD(38,"6.Periyot", "6.P"),
    SEVENTH_PERIOD(39,"7.Periyot", "7.P"),
    EIGHTH_PERIOD(40,"8.Periyot", "8.P"),
    NINTH_PERIOD(41,"9.Periyot", "9.P"),
    SIXTH_SET(42, "6.S"),
    SEVENTH_SET(43, "7.S"),
    EIGHTH_SET(44, "8.S"),
    NINTH_SET(45, "9.S"),
    TENTH_SET(46, "10.S"),
    FIRST_INNING(47, "1.D"),
    SECOND_INNING(48, "2.D"),
    BREAK(49, "D.A"),
    DAY_1(50, "1.G"),
    END_OF_FIRST_DAY(51, "1.GS"),
    DAY_2(52, "2.G"),
    END_OF_SECOND_DAY(53, "2.GS"),
    DAY_3(54, "3.G"),
    END_OF_THIRD_DAY(55, "3.GS"),
    DAY_4(56, "4.G"),
    END_OF_FOURTH_DAY(57, "4.GS"),
    DAY_5(58, "5.G"),
    END_OF_FIFTH_DAY(59, "5.GS"),
    EXTRA_TIME(60, "UZ"),
    CLOSED(61, "MS"),
    OVERTIME(62, "UZ"),
    INTERRUPTED(63, "ARA"),
    MATCH_ABOUT_TO_START(64, "MBÜ"),
    PAUSE_BETWEEN_1_ST_AND_2_ND_OVERTIME_PERIOD(65, "UZA"),
    OVERTIME_HAS_FINISHED(66, "UZS"),
    SUSPENDED(67, "ERT"),
    PLAYER_WON_THE_MATCH_BY_WALKOVER(68, "HKMN"),
    MATCH_HAS_ENDED_BECAUSE_A_PLAYER_HAS_RETIRED(69, "HKMN"),
    HOME_WIN_BY_WALKOVER(70, "HKMN"),
    AWAY_WIN_BY_WALKOVER(71, "HKMN"),
    FIRST_QUARTER(72, sportsBookText = "1.Periyot", abbr = "1.P"),
    FIRST_PAUSE(73, sportsBookText = "2.Periyot", abbr = "2.P"),
    SECOND_QUARTER(74, sportsBookText = "2.Periyot", abbr = "2.P"),
    SECOND_PAUSE(75, sportsBookText = "3.Periyot", abbr = "3.P"),
    THIRD_QUARTER(76, sportsBookText = "3.Periyot", abbr = "3.P"),
    THIRD_PAUSE(77, sportsBookText = "4.Periyot", abbr = "4.P"),
    FOURTH_QUARTER(78, sportsBookText = "4.Periyot", abbr = "4.P"),
    FOURTH_PAUSE(79, sportsBookText = "4.Periyot", abbr = "4.P"),
    FIRST_GAME(80, "1.O"),
    SECOND_GAME(81, "2.O"),
    THIRD_GAME(82, "3.O"),
    FOURTH_GAME(83, "4.O"),
    FIFTH_GAME(84, "5.O"),
    SIXTH_GAME(85, "6.O"),
    SEVENTH_GAME(86, "7.O"),
    GOLDEN_SET(87, "A.S"),
    VOLLEYBALL_MATCH_HAS_ENDED_AFTER_GOLDEN_SET(88, "MS"),
    SUDDEN_DEATH(89, "UZ"),
    FIRST_INNINGS_TOP(90, "1.D ÜST"),
    BREAK_FIRST_TOP_FIRST_BOTTOM(91, "ÜA D"),
    FIRST_INNINGS_BOTTOM(92, "1.D ALT"),
    BREAK_SECOND_TOP_FIRST_BOTTOM(93, "ÜA D"),
    SECOND_INNINGS_TOP(94, "2.D ÜST"),
    BREAK_SECOND_TOP_SECOND_BOTTOM(95, "ÜA D"),
    SECOND_INNINGS_BOTTOM(96, "2.D ALT"),
    BREAK_THIRD_TOP_SECOND_BOTTOM(97, "ÜA D"),
    THIRD_INNINGS_TOP(98, "3.D ÜST"),
    BREAK_THIRD_TOP_THIRD_BOTTOM(99, "ÜA D"),
    THIRD_INNINGS_BOTTOM(100, "3.D ALT"),
    BREAK_FOURTH_TOP_THIRD_BOTTOM(101, "ÜA D"),
    FOURTH_INNINGS_TOP(102, "4.D ÜST"),
    BREAK_FOURTH_TOP_FOURTH_BOTTOM(103, "ÜA D"),
    FOURTH_INNINGS_BOTTOM(104, "4.D ALT"),
    FIFTH_INNINGS_TOP(105, "5.D ÜST"),
    BREAK_FIFTH_TOP_FIFTH_BOTTOM(106, "ÜA D"),
    FIFTH_INNINGS_BOTTOM(107, "5.D ALT"),
    SIXTH_INNINGS_TOP(108, "6.D ÜST"),
    BREAK_SIXTH_TOP_SIXTH_BOTTOM(109, "ÜA D"),
    SIXTH_INNINGS_BOTTOM(110, "6.D ALT"),
    BREAK_SEVENTH_TOP_SIXTH_BOTTOM(111, "ÜA D"),
    SEVENTH_INNINGS_TOP(112, "7.D ÜST"),
    BREAK_SEVENTH_TOP_SEVENTH_BOTTOM(113, "ÜA D"),
    SEVENTH_INNINGS_BOTTOM(114, "7.D ALT"),
    BREAK_EIGHTH_TOP_SEVENTH_BOTTOM(115, "ÜA D"),
    EIGHTH_INNINGS_TOP(116, "8.D ÜST"),
    BREAK_EIGHTH_TOP_EIGHTH_BOTTOM(117, "ÜA D"),
    EIGHTH_INNINGS_BOTTOM(118, "8.D ALT"),
    BREAK_NINTH_TOP_EIGHTH_BOTTOM(119, "ÜA D"),
    NINTH_INNINGS_TOP(120, "9.D ÜST"),
    FIRST_END(121, "1.DS"),
    SECOND_END(122, "2.DS"),
    THIRD_END(123, "3.DS"),
    FORTH_END(124, "4.DS"),
    FIFTH_END(125, "5.DS"),
    SIXTH_END(126, "6.DS"),
    SEVENTH_END(127, "7.DS"),
    EIGHT_END(128, "8.DS"),
    NINTH_END(129, "9.DS"),
    TENTH_END(130, "10.DS"),
    THIRD_INNING(131, "3.D"),
    FOURTH_INNING(132, "4.D"),
    EXTRA_INNING(133, "UZ.D"),
    BREAK_BETWEEN_FIRST_AND_SECOND_INNINGS(134, "DA"),
    BREAK_BETWEEN_SECOND_AND_THIRD_INNINGS(135, "DA"),
    BREAK_BETWEEN_THIRD_AND_FOURTH_INNINGS(136, "DA"),
    BREAK_BETWEEN_FOURTH_AND_EXTRA_INNINGS(137, "DA"),
    ELEVENTH_SET(138, "11.S"),
    TWELFTH_SET(139, "12.S"),
    THIRTEENTH_SET(140, "13.S"),
    FIRST_MAP(141, "1.H"),
    SECOND_MAP(142, "2.H"),
    THIRD_MAP(143, "3.H"),
    FOURTH_MAP(144, "4.H"),
    FIFTH_MAP(145, "5.H"),
    FIFTH_PAUSE(146, "5.A"),
    SIXTH_MAP(147, "6.H"),
    SIXTH_PAUSE(148, "6.A"),
    SEVENTH_MAP(149, "7.H"),
    BREAK_NINTH_TOP_NINTH_BOTTOM(150, "ÜA D"),
    NINTH_INNINGS_BOTTOM(151, "9.D ALT"),
    BREAK_EI_TOP_NINTH_BOTTOM(152, "ÜA D"),
    EXTRA_INNINGS_TOP(153, "UZ.D ÜST"),
    BREAK_EI_TOP_EI_BOTTOM(154, "ÜA D"),
    EXTRA_INNINGS_BOTTOM(155, "UZ.D ALT"),
    MATCH_IS_IN_PROGRESS(156, "MO");

    companion object {
        fun getFromValue(value: Int): MatchScoreStatus {
            return values().find { it.value == value } ?: SCHEDULED
        }
    }

    fun isActive(): Boolean {
        return when (value) {
            SCHEDULED.value,
            FINISHED_AFTER_EXTRA_TIME.value,
            FINISHED_AFTER_PENALTIES.value,
            FULL_TIME.value,
            OVERTIME_HAS_FINISHED.value,
            ENDED.value,
            MATCH_HAS_ENDED_BECAUSE_A_PLAYER_HAS_RETIRED.value,
            VOLLEYBALL_MATCH_HAS_ENDED_AFTER_GOLDEN_SET.value,
            INTERRUPTED.value,
            POSTPONED.value,
            CANCELLED.value,
            CLOSED.value,
            ABANDONED.value,
            SUDDEN_DEATH.value -> false
            else -> true
        }
    }
}